config/routes.rb
Rails.application.routes.draw do
  resources :id_providers
  resource :id_provider
  resources :ldap_attributes
  resources :idp_attribute_assigns
  resources :idp_attributes
  resources :service_providers
  resources :accounts, constraints: {id: /[^\/]+/}

  match 'ldap(/:action(/:id(.format)))', controller: 'ldap', via: [:get, :post]
  match 'id_p/update_settings', controller: 'id_providers', action: 'update_settings', via: [:get, :post]

  root 'id_providers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/idp_attribute.rb
class IdpAttribute < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :idp_attribute_assigns
  has_many :service_providers, through: :idp_attribute_assigns
end

app/controllers/idp_attributes_controller.rb
class IdpAttributesController < ApplicationController
  before_action :set_idp_attribute, only: [:show, :edit, :update, :destroy]

  # GET /idp_attributes
  # GET /idp_attributes.json
  def index
    @idp_attributes = IdpAttribute.all
  end

  # GET /idp_attributes/1
  # GET /idp_attributes/1.json
  def show
  end

  # GET /idp_attributes/new
  def new
    @idp_attribute = IdpAttribute.new
  end

  # GET /idp_attributes/1/edit
  def edit
  end

  # POST /idp_attributes
  # POST /idp_attributes.json
  def create
    @idp_attribute = IdpAttribute.new(idp_attribute_params)

    respond_to do |format|
      if @idp_attribute.save
        format.html { redirect_to @idp_attribute, notice: 'IdP attribute was successfully created.' }
        format.json { render :show, status: :created, location: @idp_attribute }
        format.js { @status = 'success'}
      else
        format.html { render :new }
        format.json { render json: @idp_attribute.errors, status: :unprocessable_entity }
        format.js { @status = 'fail' }
      end
    end
  end

  # PATCH/PUT /idp_attributes/1
  # PATCH/PUT /idp_attributes/1.json
  def update
    respond_to do |format|
      if @idp_attribute.update(idp_attribute_params)
        format.html { redirect_to @idp_attribute, notice: 'IdP attribute was successfully updated.' }
        format.json { render :show, status: :ok, location: @idp_attribute }
        format.js { @status = 'success'}
      else
        format.html { render :edit }
        format.json { render json: @idp_attribute.errors, status: :unprocessable_entity }
        format.js { @status = 'fail' }
      end
    end
  end

  # DELETE /idp_attributes/1
  # DELETE /idp_attributes/1.json
  def destroy
  #  @idp_attribute.destroy
    respond_to do |format|
      format.html { redirect_to idp_attributes_url, notice: 'IdP attribute can not be destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idp_attribute
      @idp_attribute = IdpAttribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idp_attribute_params
      params.require(:idp_attribute).permit(:order, :name, :attribute_resolver, :enable)
    end
end

app/helpers/idp_attributes_helper.rb
module IdpAttributesHelper
end

app/views/idp_attributes/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">IdP attribute</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<%= form_with(model: idp_attribute, remote: true) do |form| %>
    <div class="modal-body">
    <%= render "modal_error", idp_attribute: idp_attribute %>

    <div class="form-group field">
      <strong><%= form.label :order %></strong>
      <%= form.number_field :order, id: :idp_attribute_order, class: "form-control"  %>
    </div>

    <div class="form-group field">
      <strong><%= form.label :name %></strong>
      <%= form.text_field :name, id: :idp_attribute_name, class: "form-control"  %>
    </div>

    <div class="form-group field">
      <strong><%= form.label :attribute_resolver %></strong>
      <%= form.text_area :attribute_resolver, id: :idp_attribute_attribute_resolver, rows:10, class: "form-control"  %>
    </div>

    <div class="checkbox field">
      <strong><%= form.label :enable %></strong>
      <%= form.check_box :enable, id: :idp_attribute_enable %>
    </div>
  </div>

  <div class="modal-footer actions">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/idp_attributes/_modal_error.html.erb
  <div id="modal_error">
    <% if idp_attribute.errors.any? %>
      <div id="error_explanation" class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong><%= pluralize(idp_attribute.errors.count, "error") %> prohibited this idp_attribute from being saved:</strong>

        <ul>
        <% idp_attribute.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

app/views/idp_attributes/_show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">IdP Attribute</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <div class="modal-body">
<p id="notice"><%= notice %></p>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Order</label></strong>
  <div class="form-control">
    <%= @idp_attribute.order %>
  </div>
</div>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Name</label></strong>
  <div class="form-control">
    <%= @idp_attribute.name %>
  </div>
</div>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Attribute Resolver</label></strong>
  <div class="form-control">
    <%= @idp_attribute.attribute_resolver %>
  </div>
</div>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Enable</label></strong>
  <%= @idp_attribute.enable %>
</div>

  </div>

  <div class="modal-footer actions">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
  </div>
  </div>
</div>

app/views/idp_attributes/_tr.html.erb
      <tr id="attr-ia-<%= idp_attribute.id %>">
        <td><%= idp_attribute.order %></td>
        <td><%= idp_attribute.name %></td>
        <td><%= idp_attribute.enable %></td>
        <td>
          <%= link_to 'Show', idp_attribute, remote: true, class: "btn btn-sm btn-secondary"  %>
          <%= link_to 'Edit', edit_idp_attribute_path(idp_attribute), remote: true, class: "btn btn-sm btn-secondary" %>
        </td>
      </tr>

app/views/idp_attributes/create.js.erb
<% if @status == 'success' %>
$("tbody").append("<%= j(render("tr", idp_attribute: @idp_attribute)) %>");
$("#idp_attribute-modal").modal("hide");
<%  elsif @status == 'fail' %>
$("#modal_error").replaceWith("<%= j(render("modal_error", idp_attribute: @idp_attribute)) %>");
<% end %>

app/views/idp_attributes/edit.html.erb
<h1>Editing idp Attribute</h1>

<%= render 'form', idp_attribute: @idp_attribute %>

<%= link_to 'Show', @idp_attribute %> |
<%= link_to 'Back', idp_attributes_path %>

app/views/idp_attributes/edit.js.erb
$("#idp_attribute-modal").html("<%= escape_javascript(render 'form', idp_attribute: @idp_attribute) %>")
$("#idp_attribute-modal").modal("show")

app/views/idp_attributes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>IdP Attributes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Order</th>
      <th>Name</th>
      <th>Enable</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @idp_attributes.each do |idp_attribute| %>
      <%= render "tr", idp_attribute: idp_attribute %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New idp Attribute', new_idp_attribute_path, remote: true, class: "btn btn-lg btn-primary" %>
<div id="idp_attribute-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/idp_attributes/new.html.erb
<h1>New idp Attribute</h1>

<%= render 'form', idp_attribute: @idp_attribute %>

<%= link_to 'Back', idp_attributes_path %>

app/views/idp_attributes/new.js.erb
$("#idp_attribute-modal").html("<%= escape_javascript(render 'form', idp_attribute: @idp_attribute) %>")
$("#idp_attribute-modal").modal("show")

app/views/idp_attributes/show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">IdP Attribute</h5>
    </div>
  <div class="modal-body">
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @idp_attribute.order %>
</p>

<p>
  <strong>Name:</strong>
  <%= @idp_attribute.name %>
</p>

<p>
  <strong>Attribute resolver:</strong>
  <%= @idp_attribute.attribute_resolver %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @idp_attribute.enable %>
</p>

  </div>

  <div class="modal-footer actions">
<%= link_to 'Edit', edit_idp_attribute_path(@idp_attribute) %> |
<%= link_to 'Back', idp_attributes_path %>
  </div>
  </div>
</div>

app/views/idp_attributes/show.js.erb
$("#idp_attribute-modal").html("<%= escape_javascript(render 'show', idp_attribute: @idp_attribute) %>")
$("#idp_attribute-modal").modal("show")

app/views/idp_attributes/update.js.erb
<% if @status == 'success' %>
$("#attr-ia-<%= @idp_attribute.id %>").replaceWith("<%= j(render("tr", idp_attribute: @idp_attribute)) %>");
$("#idp_attribute-modal").modal("hide");
<%  elsif @status == 'fail' %>
$("#modal_error").replaceWith("<%= j(render("modal_error", idp_attribute: @idp_attribute)) %>");
<% end %>