config/routes.rb
Rails.application.routes.draw do
  resources :id_providers
  resource :id_provider
  resources :ldap_attributes
  resources :idp_attribute_assigns
  resources :idp_attributes
  resources :service_providers
  resources :accounts, constraints: {id: /[^\/]+/}

  match 'ldap(/:action(/:id(.format)))', controller: 'ldap', via: [:get, :post]
  match 'id_p/update_settings', controller: 'id_providers', action: 'update_settings', via: [:get, :post]

  root 'id_providers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ldap_attribute.rb
class LdapAttribute < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validate :name_shuld_be_take_from_ldap_schema

  def name_shuld_be_take_from_ldap_schema
    unless Account.new.have_attribute?(name)
      errors.add(:name, ': name should be take from ldap schema')
    end
  end

  def self.attribute_names
    self.where(enable: true).order(:order).pluck(:name)
  end

  def field_type
    FieldType.find(field_type_id)
  end
end

app/controllers/ldap_attributes_controller.rb
class LdapAttributesController < ApplicationController
  before_action :set_ldap_attribute, only: [:show, :edit, :update, :destroy]

  # GET /ldap_attributes
  # GET /ldap_attributes.json
  def index
    @ldap_attributes = LdapAttribute.all
  end

  # GET /ldap_attributes/1
  # GET /ldap_attributes/1.json
  def show
  end

  # GET /ldap_attributes/new
  def new
    @ldap_attribute = LdapAttribute.new
  end

  # GET /ldap_attributes/1/edit
  def edit
  end

  # POST /ldap_attributes
  # POST /ldap_attributes.json
  def create
    @ldap_attribute = LdapAttribute.new(ldap_attribute_params)

    respond_to do |format|
      if @ldap_attribute.save
        format.html { redirect_to @ldap_attribute, notice: 'Ldap attribute was successfully created.' }
        format.json { render :show, status: :created, location: @ldap_attribute }
        format.js { @status = 'success'}
      else
        format.html { render :new }
        format.json { render json: @ldap_attribute.errors, status: :unprocessable_entity }
        format.js { @status = 'fail' }
      end
    end
  end

  # PATCH/PUT /ldap_attributes/1
  # PATCH/PUT /ldap_attributes/1.json
  def update
    respond_to do |format|
      if @ldap_attribute.update(ldap_attribute_params)
        format.html { redirect_to @ldap_attribute, notice: 'Ldap attribute was successfully updated.' }
        format.json { render :show, status: :ok, location: @ldap_attribute }
        format.js { @status = 'success'}
      else
        format.html { render :edit }
        format.json { render json: @ldap_attribute.errors, status: :unprocessable_entity }
        format.js { @status = 'fail' }
      end
    end
  end

  # DELETE /ldap_attributes/1
  # DELETE /ldap_attributes/1.json
  def destroy
    @ldap_attribute.destroy
    respond_to do |format|
      format.html { redirect_to ldap_attributes_url, notice: 'Ldap attribute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ldap_attribute
      @ldap_attribute = LdapAttribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ldap_attribute_params
      params.require(:ldap_attribute).permit(:order, :name, :field_type_id, :enable)
    end
end

app/helpers/ldap_attributes_helper.rb
module LdapAttributesHelper
end

app/views/ldap_attributes/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">LDAP attribute</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<%= form_with(model: ldap_attribute, remote: true) do |form| %>
    <div class="modal-body">
    <%= render "modal_error", ldap_attribute: ldap_attribute %>

    <div class="form-group field">
      <strong><%= form.label :order %></strong>
      <%= form.number_field :order, id: :ldap_attribute_order, class: "form-control"  %>
    </div>

    <div class="form-group field">
      <strong><%= form.label :name %></strong>
      <%= form.text_field :name, id: :ldap_attribute_name, class: "form-control"  %>
    </div>

    <div class="form-group field">
      <strong><%= form.label :field_type %></strong>
      <%= form.select( :field_type_id, FieldType.options, {prompt: 'select one'}, {id: :ldap_attribute_field_type, class: "form-control"} ) %>
    </div>

    <div class="checkbox field">
      <strong><%= form.label :enable %></strong>
      <%= form.check_box :enable, id: :ldap_attribute_enable %>
    </div>
  </div>

  <div class="modal-footer actions">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/ldap_attributes/_modal_error.html.erb
  <div id="modal_error">
    <% if ldap_attribute.errors.any? %>
      <div id="error_explanation" class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong><%= pluralize(ldap_attribute.errors.count, "error") %> prohibited this ldap_attribute from being saved:</strong>

        <ul>
        <% ldap_attribute.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

app/views/ldap_attributes/_show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">LDAP Attribute</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <div class="modal-body">
<p id="notice"><%= notice %></p>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Order</label></strong>
  <div class="form-control">
    <%= @ldap_attribute.order %>
  </div>
</div>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Name</label></strong>
  <div class="form-control">
    <%= @ldap_attribute.name %>
  </div>
</div>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Field type</label></strong>
  <div class="form-control">
    <%= @ldap_attribute.field_type.name %>
  </div>
</div>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Enable</label></strong>
  <%= @ldap_attribute.enable %>
</div>

  </div>

  <div class="modal-footer actions">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
  </div>
  </div>
</div>

app/views/ldap_attributes/_tr.html.erb
      <tr id="attr-la-<%= ldap_attribute.id %>">
        <td><%= ldap_attribute.order %></td>
        <td><%= ldap_attribute.name %></td>
        <td><%= ldap_attribute.field_type.name %></td>
        <td><%= ldap_attribute.enable %></td>
        <td>
          <%= link_to 'Show', ldap_attribute, remote: true, class: "btn btn-sm btn-secondary"  %>
          <%= link_to 'Edit', edit_ldap_attribute_path(ldap_attribute), remote: true, class: "btn btn-sm btn-secondary" %>
        </td>
      </tr>

app/views/ldap_attributes/create.js.erb
<% if @status == 'success' %>
$("tbody").append("<%= j(render("tr", ldap_attribute: @ldap_attribute)) %>");
$("#ldap_attribute-modal").modal("hide");
<%  elsif @status == 'fail' %>
$("#modal_error").replaceWith("<%= j(render("modal_error", ldap_attribute: @ldap_attribute)) %>");
<% end %>

app/views/ldap_attributes/edit.html.erb
<h1>Editing LDAP Attribute</h1>

<%= render 'form', ldap_attribute: @ldap_attribute %>

<%= link_to 'Show', @ldap_attribute %> |
<%= link_to 'Back', ldap_attributes_path %>

app/views/ldap_attributes/edit.js.erb
$("#ldap_attribute-modal").html("<%= escape_javascript(render 'form', ldap_attribute: @ldap_attribute) %>")
$("#ldap_attribute-modal").modal("show")

app/views/ldap_attributes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>LDAP Attributes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Order</th>
      <th>Name</th>
      <th>Field type</th>
      <th>Enable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ldap_attributes.each do |ldap_attribute| %>
      <%= render "tr", ldap_attribute: ldap_attribute %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ldap Attribute', new_ldap_attribute_path, remote: true, class: "btn btn-lg btn-primary" %>
<div id="ldap_attribute-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/ldap_attributes/new.html.erb
<h1>New LDAP Attribute</h1>

<%= render 'form', ldap_attribute: @ldap_attribute %>

<%= link_to 'Back', ldap_attributes_path %>

app/views/ldap_attributes/new.js.erb
$("#ldap_attribute-modal").html("<%= escape_javascript(render 'form', ldap_attribute: @ldap_attribute) %>")
$("#ldap_attribute-modal").modal("show")

app/views/ldap_attributes/show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">LDAP Attribute</h5>
    </div>
  <div class="modal-body">
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @ldap_attribute.order %>
</p>

<p>
  <strong>Name:</strong>
  <%= @ldap_attribute.name %>
</p>

<p>
  <strong>Field type:</strong>
  <%= @ldap_attribute.field_type.name %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @ldap_attribute.enable %>
</p>

  <div class="modal-footer actions">
<%= link_to 'Edit', edit_ldap_attribute_path(@ldap_attribute) %> |
<%= link_to 'Back', ldap_attributes_path %>
  </div>
  </div>
</div>

app/views/ldap_attributes/show.js.erb
$("#ldap_attribute-modal").html("<%= escape_javascript(render 'show', ldap_attribute: @ldap_attribute) %>")
$("#ldap_attribute-modal").modal("show")

app/views/ldap_attributes/update.js.erb
<% if @status == 'success' %>
$("#attr-la-<%= @ldap_attribute.id %>").replaceWith("<%= j(render("tr", ldap_attribute: @ldap_attribute)) %>");
$("#ldap_attribute-modal").modal("hide");
<%  elsif @status == 'fail' %>
$("#modal_error").replaceWith("<%= j(render("modal_error", ldap_attribute: @ldap_attribute)) %>");
<% end %>