config/routes.rb
Rails.application.routes.draw do
  resources :id_providers
  resource :id_provider
  resources :ldap_attributes
  resources :idp_attribute_assigns
  resources :idp_attributes
  resources :service_providers
  resources :accounts, constraints: {id: /[^\/]+/}

  match 'ldap(/:action(/:id(.format)))', controller: 'ldap', via: [:get, :post]
  match 'id_p/update_settings', controller: 'id_providers', action: 'update_settings', via: [:get, :post]

  root 'id_providers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service_provider.rb
class ServiceProvider < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :entity_id, uniqueness: true

  has_many :idp_attribute_assigns
  has_many :idp_attributes, through: :idp_attribute_assigns
end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController
  before_action :set_service_provider, only: [:show, :edit, :update, :destroy]

  # GET /service_providers
  # GET /service_providers.json
  def index
    @service_providers = ServiceProvider.all
  end

  # GET /service_providers/1
  # GET /service_providers/1.json
  def show
  end

  # GET /service_providers/new
  def new
    @service_provider = ServiceProvider.new
  end

  # GET /service_providers/1/edit
  def edit
  end

  # POST /service_providers
  # POST /service_providers.json
  def create
    @service_provider = ServiceProvider.new(service_provider_params)

    respond_to do |format|
      if @service_provider.save
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully created.' }
        format.json { render :show, status: :created, location: @service_provider }
        format.js { @status = 'success'}
      else
        format.html { render :new }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
        format.js { @status = 'fail' }
      end
    end
  end

  # PATCH/PUT /service_providers/1
  # PATCH/PUT /service_providers/1.json
  def update
    respond_to do |format|
      if @service_provider.update(service_provider_params)
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_provider }
        format.js { @status = 'success'}
      else
        format.html { render :edit }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
        format.js { @status = 'fail' }
      end
    end
  end

  # DELETE /service_providers/1
  # DELETE /service_providers/1.json
  def destroy
    @service_provider.destroy
    respond_to do |format|
      format.html { redirect_to service_providers_url, notice: 'Service provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_provider
      @service_provider = ServiceProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_provider_params
      params.require(:service_provider).permit(:name, :entity_id, :metadata, :enable)
    end
end

app/helpers/service_providers_helper.rb
module ServiceProvidersHelper
end

app/views/service_providers/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Service Provider</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<%= form_with(model: service_provider, remote: true) do |form| %>
    <div class="modal-body">
    <%= render "modal_error", service_provider: service_provider %>

    <div class="form-group field">
      <strong><%= form.label :name, class: 'control-label col-lg-2' %></strong>
      <%= form.text_field :name, id: :service_provider_name, class: "form-control" %>
    </div>

    <div class="form-group field">
      <strong><%= form.label :entity_id, 'EntityID', class: 'control-label col-lg-2' %></strong>
      <%= form.text_field :entity_id, id: :service_provider_entity_id, class: "form-control" %>
    </div>

    <div class="form-group field">
      <strong><%= form.label :metadata, class: 'control-label col-lg-2' %></strong>
      <%= form.text_area :metadata, id: :service_provider_metadata, rows: 10, class: "form-control" %>
    </div>

    <div class="checkbox field">
      <strong><%= form.label :enable, class: 'control-label col-lg-2' %></strong>
      <%= form.check_box :enable, id: :service_provider_enable %>
    </div>
  </div>

  <div class="modal-footer actions">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
  </div>
</div>

app/views/service_providers/_modal_error.html.erb
  <div id="modal_error">
    <% if service_provider.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(service_provider.errors.count, "error") %> prohibited this service_provider from being saved:</h2>

        <ul>
        <% service_provider.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

app/views/service_providers/_show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Service Provider</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <div class="modal-body">
<p id="notice"><%= notice %></p>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Name</label></strong>
  <div class="form-control">
    <%= @service_provider.name %>
  </div>
</div>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">EntityID</label></strong>
  <div class="form-control">
    <%= @service_provider.entity_id %>
  </div>
</div>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Metadata</label></strong>
  <div class="form-control">
    <%= @service_provider.metadata %>
  </div>
</div>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">Enable</label></strong>
  <%= @service_provider.enable %>
</div>

<div class="form-group field">
  <strong><label class="control-label col-lg-2">SendAttributes</label></strong>
  <div class="form-control">
    <%= @service_provider.idp_attributes.map(&:name).join(', ') %>
  </div>
</div>

  </div>

  <div class="modal-footer actions">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
  </div>
  </div>
</div>

app/views/service_providers/_tr.html.erb
      <tr id="attr-sp-<%= service_provider.id %>">
        <td><%= service_provider.name %></td>
        <td><%= service_provider.entity_id %></td>
        <td><%= service_provider.enable %></td>
        <td>
          <%= link_to 'Show', service_provider, remote: true, class: "btn btn-sm btn-secondary" %>
          <%= link_to 'Edit', edit_service_provider_path(service_provider), remote: true, class: "btn btn-sm btn-secondary" %>
          <%= link_to 'Attribute', edit_idp_attribute_assign_path(service_provider), remote: true, class: "btn btn-sm btn-secondary" %>
          <%= link_to 'Destroy', service_provider, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        </td>
      </tr>

app/views/service_providers/create.js.erb
<% if @status == 'success' %>
$("tbody").append("<%= j(render("tr", service_provider: @service_provider)) %>");
$("#service_provider-modal").modal("hide");
<%  elsif @status == 'fail' %>
$("#modal_error").replaceWith("<%= j(render("modal_error", service_provider: @service_provider)) %>");
<% end %>

app/views/service_providers/edit.html.erb
<h1>Editing Service Provider</h1>

<%= render 'form', service_provider: @service_provider %>

<%= link_to 'Show', @service_provider %> |
<%= link_to 'Back', service_providers_path %>

app/views/service_providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Providers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>EntityID</th>
      <th>Enable</th>
      <th</th>
    </tr>
  </thead>

  <tbody>
    <% @service_providers.each do |service_provider| %>
      <%= render "tr", service_provider: service_provider %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Provider', new_service_provider_path, remote: true, class: "btn btn-lg btn-primary" %>
<div id="service_provider-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/service_providers/new.html.erb
<h1>New Service Provider</h1>

<%= render 'form', service_provider: @service_provider %>

<%= link_to 'Back', service_providers_path %>

app/views/service_providers/new.js.erb
$("#service_provider-modal").html("<%= escape_javascript(render 'form', service_provider: @service_provider) %>")
$("#service_provider-modal").modal("show")

app/views/service_providers/show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Service Provider</h5>
    </div>
  <div class="modal-body">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service_provider.name %>
</p>

<p>
  <strong>EntityID:</strong>
  <%= @service_provider.entity_id %>
</p>

<p>
  <strong>Metadata:</strong>
  <%= @service_provider.metadata %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @service_provider.enable %>
</p>

  </div>

  <div class="modal-footer actions">
    <%= link_to 'Edit', edit_service_provider_path(@service_provider) %> |
    <%= link_to 'Back', service_providers_path %>
  </div>
  </div>
</div>

app/views/service_providers/show.js.erb
$("#service_provider-modal").html("<%= escape_javascript(render 'show', service_provider: @service_provider) %>")
$("#service_provider-modal").modal("show")

app/views/service_providers/update.js.erb
<% if @status == 'success' %>
$("#attr-sp-<%= @service_provider.id %>").replaceWith("<%= j(render("tr", service_provider: @service_provider)) %>");
$("#service_provider-modal").modal("hide");
<%  elsif @status == 'fail' %>
$("#modal_error").replaceWith("<%= j(render("modal_error", service_provider: @service_provider)) %>");
<% end %>