config/routes.rb
Rails.application.routes.draw do
  resources :id_providers
  resource :id_provider
  resources :ldap_attributes
  resources :idp_attribute_assigns
  resources :idp_attributes
  resources :service_providers
  resources :accounts, constraints: {id: /[^\/]+/}

  match 'ldap(/:action(/:id(.format)))', controller: 'ldap', via: [:get, :post]
  match 'id_p/update_settings', controller: 'id_providers', action: 'update_settings', via: [:get, :post]

  root 'id_providers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ActiveLdap::Base
  ldap_mapping dn_attribute: "uid",
               prefix: "ou=accounts",
               classes: ['inetOrgPerson', 'eduPerson'],
               scope: :one
  before_create :digest_password
  before_update :digest_password
  before_validation :dup_user_name

  def digest_password
    return if user_password.blank? || /\{MD5\}/ =~ user_password
    password_digest = '{MD5}' + Base64.encode64(Digest::MD5.digest(user_password)).chomp
    self.user_password = password_digest
  end

  def dup_user_name
    self.cn = displayName
    self.sn = displayName
  rescue
    # fix for ActiveLdap::Populate#ensure_ou bug.
    # it calls this callback illegally.
   true
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params.to_hash)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
        format.js { @status = 'success'}
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
        format.js { @status = 'fail' }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update_attributes(account_params.tap{|account|
          account[:user_password] = @account.user_password if account[:user_password].blank?
        })
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
        format.js { @status = 'success'}
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
        format.js { @status = 'fail' }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      attribute_names = LdapAttribute.attribute_names.map{|n| n.underscore.to_sym}
      account = params.require(:account).permit(*attribute_names)
      account
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Account</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<%= form_with(model: account, remote: true) do |form| %>
    <div class="modal-body">
    <%= render "modal_error", account: account %>

<% LdapAttribute.order(:order).each do |ldap_attribute| -%>
    <div class="form-group field">
      <strong><%= form.label ldap_attribute.name, class: 'control-label col-lg-2' %></strong>
      <% meth, options = ldap_attribute.field_type.form %>
      <% options[:id] = ldap_attribute.name.underscore %>
      <%= form.send(meth.to_sym, ldap_attribute.name.underscore.to_sym, options) %>
    </div>
<% end -%>
    </div>

  <div class="modal-footer actions">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>
  </div>
</div>

app/views/accounts/_modal_error.html.erb
  <div id="modal_error">
    <% if account.errors.any? %>
      <div id="error_explanation" class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</strong>

        <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

app/views/accounts/_show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Account</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <div class="modal-body">
<p id="notice"><%= notice %></p>

<% LdapAttribute.order(:order).each do |ldap_attribute| -%>
<div class="form-group field">
  <strong><label class="control-label col-lg-2"><%= ldap_attribute.name %></label></strong>
  <div class="form-control">
<% if ldap_attribute.field_type.display -%>
    <%= ldap_attribute.field_type.display %>
<% else -%>
    <%= @account.send(ldap_attribute.name.to_sym) %>
<% end -%>
  </div>
</div>
<% end -%>

  </div>

  <div class="modal-footer actions">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
  </div>
  </div>
</div>

app/views/accounts/_tr.html.erb
      <tr id="attr-ac-<%= account.id %>">
        <td><%= account.display_name %></td>
        <td><%= account.mail %></td>
        <td><%= account.uid %></td>
        <td>
          <%= link_to 'Show', account, remote: true, class: "btn btn-sm btn-secondary" %>
          <%= link_to 'Edit', edit_account_path(account), remote: true, class: "btn btn-sm btn-secondary" %>
          <%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        </td>
      </tr>

app/views/accounts/create.js.erb
<% if @status == 'success' %>
$("tbody").append("<%= j(render("tr", account: @account)) %>");
$("#account-modal").modal("hide");
<%  elsif @status == 'fail' %>
$("#modal_error").replaceWith("<%= j(render("modal_error", account: @account)) %>");
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account/h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/edit.js.erb
$("#account-modal").html("<%= escape_javascript(render 'form', account: @account) %>")
$("#account-modal").modal("show")

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Mail</th>
      <th>UID</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <%= render "tr", account: account %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path, remote: true, class: "btn btn-lg btn-primary" %>
<div id="account-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/accounts/new.html.erb
<h1>Account</h1>

<%= render 'form', account: @account %>

<%#= link_to 'Back', account_path %>

app/views/accounts/new.js.erb
$("#account-modal").html("<%= escape_javascript(render 'form', account: @account) %>")
$("#account-modal").modal("show")

app/views/accounts/show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Account</h5>
    </div>
  <div class="modal-body">
<p id="notice"><%= notice %></p>

<% LdapAttribute.order(:order).each do |ldap_attribute| -%>
<p>
  <strong><%= ldap_attribute.name %>:</strong>
<% if ldap_attribute.field_type.display -%>
  <%= ldap_attribute.field_type.display %>
<% else -%>
  <%= @account.send(ldap_attribute.name.to_sym) %>
<% end -%>
</p>
<% end -%>

  </div>

  <div class="modal-footer actions">
<%= link_to 'Edit', edit_account_path(@account) %> |
<%#= link_to 'Back', account_path %>
  </div>
  </div>
</div>

app/views/accounts/show.js.erb
$("#account-modal").html("<%= escape_javascript(render 'show', account: @account) %>")
$("#account-modal").modal("show")

app/views/accounts/update.js.erb
<% if @status == 'success' %>
$("#attr-ac-<%= @account.id %>").replaceWith("<%= j(render("tr", account: @account)) %>");
$("#account-modal").modal("hide");
<%  elsif @status == 'fail' %>
$("#modal_error").replaceWith("<%= j(render("modal_error", account: @account)) %>");
<% end %>